-- =============================================================================
-- Aligner Portal — Phase 3b ANNOUNCEMENTS + ACTIVITY FLAGS (run on the Supabase mirror)
-- =============================================================================
--
-- Prereq: the main app's migrations/supabase/announcements-2026-07-11.sql has been
-- applied (creates doctor_announcements / doctor_announcement_reads and adds the
-- `source` column + widened ck_activitytype to aligner_activity_flags).
--
-- This script opens exactly three portal surfaces — and nothing else:
--
--   1. READ ANNOUNCEMENTS  → SELECT on doctor_announcements (broadcast rows OR rows
--      targeted at the caller's dr_id). Staff-authored, forward-synced from the
--      clinic; the portal never writes this table.
--   2. DISMISS / MARK READ → INSERT into doctor_announcement_reads (own dr_id, and
--      only for an announcement the caller can see). Reverse-syncs home like
--      aligner_notes (updated_at + cdc_capture_remote, EVEN ids). Dismiss-all is a
--      batch of these inserts with ignoreDuplicates (ON CONFLICT DO NOTHING) — no
--      UPDATE grant, receipts are immutable once written.
--   3. FLAG STAFF ACTIVITY → INSERT into aligner_activity_flags with source='portal'
--      (forced by policy), one of the four activity types, on the caller's OWN set,
--      arriving unread (is_read=false). This feeds the staff app's "Portal activity"
--      header bell after reverse sync. No SELECT grant — the portal writes flags
--      blind and never reads them back.
--
-- WHY these mirror writes are safe: both writable tables carry updated_at, so they
-- are in the REVERSE-SYNC set (see sql/phase2-writes.sql for the full argument).
-- cdc_capture_remote() must be the SECURITY DEFINER build (reverse-cdc.sql §3) —
-- `authenticated` holds no change_log privileges.
--
-- Scope discipline (same as Phases 1/2): grants are COLUMN-level and RLS is per-row.
-- is_read is NOT granted on aligner_activity_flags — its DEFAULT is already false
-- (unlike aligner_notes' TRUE), so the portal simply omits it; the policy still pins
-- is_read=false so a future default flip fails loudly instead of arriving pre-read.
--
-- Safe to re-run (policies dropped + recreated; GRANTs are idempotent).
-- =============================================================================

begin;

-- ---- doctor_announcements : broadcast rows or rows targeted at the caller ----
-- (ENABLE is an idempotent no-op — announcements-2026-07-11.sql already enabled it.
--  Do NOT FORCE: the failover sink writes as the table owner and must bypass RLS.)
alter table public.doctor_announcements enable row level security;

drop policy if exists portal_select on public.doctor_announcements;
create policy portal_select on public.doctor_announcements
  for select
  to authenticated
  using (
    target_doctor_id is null
    or target_doctor_id = (auth.jwt() ->> 'dr_id')::int
  );

grant select on public.doctor_announcements to authenticated;

-- ---- doctor_announcement_reads : a doctor may record (and see) their own receipts ----
alter table public.doctor_announcement_reads enable row level security;

drop policy if exists portal_select on public.doctor_announcement_reads;
create policy portal_select on public.doctor_announcement_reads
  for select
  to authenticated
  using ( dr_id = (auth.jwt() ->> 'dr_id')::int );

-- INSERT: own dr_id, and only for an announcement the caller can actually see
-- (broadcast or targeted at them). NB a dismiss racing a staff-side delete fails
-- THIS check (42501), not the FK — the portal treats that as success.
drop policy if exists portal_insert on public.doctor_announcement_reads;
create policy portal_insert on public.doctor_announcement_reads
  for insert
  to authenticated
  with check (
    dr_id = (auth.jwt() ->> 'dr_id')::int
    and announcement_id in (
      select a.announcement_id
      from public.doctor_announcements a
      where a.target_doctor_id is null
         or a.target_doctor_id = (auth.jwt() ->> 'dr_id')::int
    )
  );

-- Column-level INSERT: read_id (EVEN identity), read_at (default) and updated_at
-- (remote trigger) are not settable — a doctor cannot forge them.
grant select on public.doctor_announcement_reads to authenticated;
grant insert (announcement_id, dr_id) on public.doctor_announcement_reads to authenticated;
-- Identity is GENERATED BY DEFAULT; the non-owner writer needs sequence USAGE for
-- the defaulted read_id to resolve (matches phase2-writes.sql / mirror-grants.sql).
do $$
declare seq text;
begin
  seq := pg_get_serial_sequence('public.doctor_announcement_reads', 'read_id');
  if seq is not null then
    execute format('grant usage on sequence %s to authenticated', seq);
  end if;
end $$;

-- ---- aligner_activity_flags : portal flags its own writes for the staff bell ----
-- RLS was already enabled on the mirror (verified: RLS on, zero policies — every
-- role but the owner was locked out). Kept for the record; still do NOT FORCE.
alter table public.aligner_activity_flags enable row level security;

drop policy if exists portal_insert on public.aligner_activity_flags;
create policy portal_insert on public.aligner_activity_flags
  for insert
  to authenticated
  with check (
    source = 'portal'
    and is_read = false
    and activity_type in ('DaysChanged', 'DoctorNote', 'PhotoUploaded', 'FileUploaded')
    and aligner_set_id in (
      select s.aligner_set_id
      from public.aligner_sets s
      where s.aligner_dr_id = (auth.jwt() ->> 'dr_id')::int
    )
  );

-- No SELECT grant (write-only surface); no is_read grant (DEFAULT false is correct).
grant insert (aligner_set_id, activity_type, activity_description, related_record_id, source)
  on public.aligner_activity_flags to authenticated;
do $$
declare seq text;
begin
  seq := pg_get_serial_sequence('public.aligner_activity_flags', 'activity_id');
  if seq is not null then
    execute format('grant usage on sequence %s to authenticated', seq);
  end if;
end $$;

commit;

-- =============================================================================
-- Verification (run as needed in the SQL editor; pattern per phase2-writes.sql):
--
--   -- Simulate a doctor (replace 123 with a real dr_id, S with a set they own,
--   -- A with a broadcast/targeted announcement_id):
--   set local role authenticated;
--   set local request.jwt.claims = '{"role":"authenticated","dr_id":123}';
--
--   select count(*) from public.doctor_announcements;      -- broadcast + own only
--   insert into public.doctor_announcement_reads (announcement_id, dr_id)
--     values (A, 123);                                      -- succeeds, read_id EVEN
--   insert into public.aligner_activity_flags
--     (aligner_set_id, activity_type, activity_description, source)
--     values (S, 'PhotoUploaded', 'uploaded test.jpg', 'portal');  -- succeeds
--   reset role;
--   select * from change_log where sink='reverse'
--     and tbl in ('doctor_announcement_reads','aligner_activity_flags')
--     order by changed_at desc limit 5;                     -- both captured
--
--   -- Each of these must FAIL (RLS violation / no grant):
--   --   reads insert w/ dr_id <> claim, or for an announcement targeted elsewhere
--   --   flags insert w/ source='staff', a 5th activity_type, or a foreign set
--   --   update public.doctor_announcement_reads set read_at=now();  -- no grant
--   --   select * from public.aligner_activity_flags;                -- no grant
-- =============================================================================
