-- =============================================================================
-- Aligner Portal — Phase 2 WRITES (run in the single Supabase mirror's SQL editor)
-- =============================================================================
--
-- Phase 1 (sql/phase1-rls.sql) made the six portal tables READ-only for the
-- dr_id-scoped `authenticated` JWT. Phase 2 lets a doctor do exactly two writes —
-- and nothing else — directly against the mirror:
--
--   1. ADD A NOTE   → INSERT into aligner_notes (note_type forced to 'Doctor').
--   2. CHANGE DAYS  → UPDATE aligner_batches.days (that column only).
--
-- WHY writing to the mirror is now safe (it was NOT in Phase 1):
--   Both aligner_notes and aligner_batches carry `updated_at`, so they are in the
--   REVERSE-SYNC set. A genuine (non-failover-origin) edit here fires
--   set_updated_at_remote() (fresh stamp) + cdc_capture_remote() (records the
--   change into change_log('reverse') on Supabase). Reverse CDC v2 then applies it
--   to the clinic's local Postgres — the source of truth — under whole-row LWW by
--   updated_at. The old "forward sync overwrites portal writes" hazard is gone:
--   forward sync only pushes local→mirror when local.updated_at >= mirror.updated_at,
--   so a fresher mirror edit is preserved until reverse sync carries it home.
--   (Inserted notes get an EVEN note_id from the mirror's odd/even-split identity
--   sequence, so they never collide with local's ODD ids on apply.)
--
-- PREREQUISITE — migrations/supabase/reverse-cdc.sql must be the SECURITY DEFINER
--   version of cdc_capture_remote(). The `authenticated` role does NOT (and must
--   not) hold write grants on change_log; the capture trigger writes that feed on
--   its behalf only because it runs as its owner. If you applied an older reverse-cdc
--   build, re-apply §3 of that file first, or these writes fail
--   `permission denied for table change_log`.
--
-- Scope discipline (same as Phase 1): grants are COLUMN-level and RLS is per-row, so
--   "writable on the mirror ⟺ (a doctor's own note insert | a doctor's own batch's
--   days)". No other table, column, row, or note_type is reachable by the portal.
--
-- Safe to re-run (policies dropped + recreated; GRANTs are idempotent).
-- =============================================================================

begin;

-- ---- aligner_notes : a doctor may INSERT a 'Doctor' note on one of their sets ----
-- Column-level INSERT: only these four columns are settable. note_id (identity),
-- created_at, updated_at, is_edited are left to their defaults — a doctor cannot
-- forge them. is_read MUST be sent explicitly as false: the column's DEFAULT is
-- TRUE (verified on both DBs 2026-06-11), so an insert omitting it would arrive
-- pre-read and the lab's unread badge (note_type='Doctor' AND is_read=false)
-- would never fire. The policy below forces is_read=false, so omitting it (or
-- forging true) fails loudly rather than silently swallowing the notification.
grant insert (aligner_set_id, note_type, note_text, is_read) on public.aligner_notes to authenticated;
-- Identity is GENERATED BY DEFAULT; grant sequence USAGE so the defaulted note_id
-- resolves for a non-owner writer (belt-and-suspenders; matches mirror-grants.sql).
do $$
declare seq text;
begin
  seq := pg_get_serial_sequence('public.aligner_notes', 'note_id');
  if seq is not null then
    execute format('grant usage on sequence %s to authenticated', seq);
  end if;
end $$;

drop policy if exists portal_insert on public.aligner_notes;
create policy portal_insert on public.aligner_notes
  for insert
  to authenticated
  with check (
    note_type = 'Doctor'
    and is_read = false
    and aligner_set_id in (
      select s.aligner_set_id
      from public.aligner_sets s
      where s.aligner_dr_id = (auth.jwt() ->> 'dr_id')::int
    )
  );

-- ---- aligner_batches : a doctor may UPDATE days on one of their sets' batches ----
-- Column-level UPDATE on `days` ONLY. set_updated_at_remote() also bumps updated_at,
-- but a BEFORE-trigger's NEW assignment needs no column privilege from the writer.
grant update (days) on public.aligner_batches to authenticated;

drop policy if exists portal_update on public.aligner_batches;
create policy portal_update on public.aligner_batches
  for update
  to authenticated
  using (
    aligner_set_id in (
      select s.aligner_set_id
      from public.aligner_sets s
      where s.aligner_dr_id = (auth.jwt() ->> 'dr_id')::int
    )
  )
  with check (
    aligner_set_id in (
      select s.aligner_set_id
      from public.aligner_sets s
      where s.aligner_dr_id = (auth.jwt() ->> 'dr_id')::int
    )
  );

commit;

-- =============================================================================
-- Verification (run as needed in the SQL editor):
--
--   -- Simulate a doctor adding a note (replace 123 with a real dr_id, S with a set
--   -- that doctor owns); should INSERT exactly one row and land in change_log:
--   set local role authenticated;
--   set local request.jwt.claims = '{"role":"authenticated","dr_id":123}';
--   insert into public.aligner_notes (aligner_set_id, note_type, note_text, is_read)
--     values (S, 'Doctor', 'verification note', false);
--   reset role;
--   select * from change_log where sink='reverse' and tbl='aligner_notes'
--     order by changed_at desc limit 1;   -- expect op='I' for the new pk
--
--   -- A doctor must NOT be able to write a foreign set, a 'Lab' note, or any other
--   -- column/table — each of these should error (RLS check / no grant):
--   --   insert ... values (<other doctor's set>, 'Doctor', 'x');   -- RLS violation
--   --   insert ... values (S, 'Lab', 'x');                         -- RLS violation
--   --   update public.aligner_batches set notes='x' where ...;     -- no column grant
-- =============================================================================
